config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :advertisements 
  resources :topics do
    resources :sponsored_posts
    resources :posts, except: [:index]
  end
  
   resources :posts, only: [] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]
     
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  post 'users/confirm' => 'users#confirm'
  
  get 'about' => 'welcome#about'
  
  get 'welcome/contact'
  
  get 'welcome/faq'
  
  root 'welcome#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
    has_many :posts, dependent: :destroy
    
    validates :name, length: { minimum: 5 }, presence: true
    validates :description, length: { minimum: 15 }, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def index 
        @topics = Topic.all
    end
    
    def show
        @topic = Topic.find(params[:id])
    end
    
    def new
        @topic = Topic.new
    end
    
    def create
        @topic = Topic.new(topic_params)
        
        if @topic.save
            redirect_to @topic, notice: "Topic was saved"
        else
            flash.now[:alert] = "Error"
            render :new
        end
    end
    
    def edit
        @topic = Topic.find(params[:id])
    end
    
    def update
        @topic = Topic.find(params[:id])
        @topic.assign_attributes(topic_params)
        
        if @topic.save 
            flash[:notice] = "Topic updated."
            redirect_to @topic
        else
            flash.now[:alert] = "Error"
            render :edit
        end
    end
    
    def destroy
        @topic = Topic.find(params[:id])
        if @topic.destroy
            flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
            redirect_to action: :index
        else
            flash.now[:alert] = "Error"
            render :show
        end
    end
    
    private
    
    def topic_params
        params.require(:topic).permit(:name, :description, :public)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
    def user_is_authorized_for_topics?
        current_user && current_user.admin?
    end
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
    <% if topic.errors.any? %>
        <div class="alert alert-danger">
            
            <h4>There are <%= pluralize(topic.errors.count, "error") %>.</h4>
            <ul>
                <% topic.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= form_group_tag(topic.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter Topic Name" %>
    <% end %>
    
    <%= form_group_tag(topic.errors[:description]) do %>
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter Topic Description" %>
    <% end %>
    
    
    <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public Topic
        <% end %>
    </div>
    
    <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/topics/_topic.html.erb
<div class="media">
    <div class="media-body">
        <h4 class="media-heading">
            <%= link_to topic.name, topic %>
        </h4>
            <small>
                <%= topic.description %>
            </small>
    </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<div class="row">
    <div class="col-md-4">
        <p>Guidelines for topics:</p>
        <ul>
            <li>Make sure you dont make me type this again</li>
            <li>And again</li>
            <li>And again</li>
        </ul>
    </div>
    <div class="col-md-8">
       <%= render partial: 'form', locals: { topic: @topic } %>
    </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
    <div class="col-md-8">
        <% @topics.each do |topic| %>
          <%= render partial: 'topic', locals: {topic: topic } %>
        <% end %>
    </div>
    <% if user_is_authorized_for_topics? %>
    <div class="col-md-4">
        <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    </div>
    <% end %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidlines for topics:</p>
        <ul>
            <li>Make sure the topic is appropriate.</li>
            <li>Never insult dogs.</li>
            <li>Never make me type this dumb shit again!</li>
        </ul>
    </div>
    <div calss="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic } %>
    </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>
<% if user_is_authorized_for_topics? %>
<%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'You sure bro?' } %>
<% end %>
<div class="row">
    <div class="col-md-8">
        <p class="lead"><%= @topic.description %></p>
          <% @topic.posts.each do |post| %>
          <%= render partial: 'votes/voting', locals: { post: post } %>
          <%= render partial: 'posts/post', locals: {post: post } %>
        <% end %>
    </div>
    <% if current_user %>
    <div class="col-md-4">
        <%= link_to "New Post", new_topic_post_path(@topic), class: "btn btn-success" %>
        <%= link_to "New Sponsored Post", new_topic_sponsored_post_path(@topic), class: "btn btn-success" %>
    </div>
    <% end %>
</div>